[package]
name = "ba_credit"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
experimental-features = ["associated_item_constraints"]

[tool]
fmt.workspace = true
scarb.workspace = true


[dependencies]
starknet.workspace = true
sai_access.workspace = true
sai_ownable.workspace = true
dojo_macros.workspace = true
dojo.workspace = true
beacon_macros.workspace = true
beacon_library.workspace = true
pragma_lib.workspace = true
openzeppelin_token.workspace = true


[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = true

[dev-dependencies]
cairo_test = "2.11.4"
# dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0-alpha.2" }

[lib]
