rpc = "https://api.cartridge.gg/x/starknet/sepolia"
db_dir = "~/ba-database/sepolia"

[indexing]
contracts = [
    "erc721:0x4bc8ecaef92e9ac2e944919aa41ba86e1c3f524b9c240443945a71692a90499",
    "erc721:0x3246c0b3796cf5482a5a82251636f05928ff57a64f9acf816e09cf30b6dc31f",
    "erc721:0x7b365b9fb5f7f6a0825b9fad8419531a3329f79f2f7370565ddb923bf2db903",
    "contract:0x36844d227e8db442b49e2b89df5a999b3f87dab287aa99870425da6603b742c",
    "contract:0x6728500ef8b1e72a523d506f0582ba7ffecdada16291c840afc2d2b178eafa5",
    "contract:0x2a5d732c9d328c7e879564ca4dfc1d36020b5ea764919f4bbc98a2c0d0053c8",
    "contract:0x135e451868027bab0e2a7cf17ed86c156ac164419dc3dc6d4159cb1bc37a174",
    "contract:0x1b9a64fef0a2384fb20b080c9008560ac32eaff69349fd3b101b072543914e3",
    "contract:0x6fc488e7d314dc19c6c4fcde58bccc8d6df1ae0058beb7506e44a6097822b6d",
    "contract:0x1a3f11d9cbd28c5a27a7e8f750d7f4fe4e00d1717558c7de2bf37ffee6bf24a",
    "contract:0x2a6a00cec30f3ff545576c102f4ff9d6f98edcc0440d8d57431054a3a534793",
    "contract:0x51ff016d350bfdcdc80c808ada3768299a295d09a49fd18ceed4b4fe402bfb1",
]
